---
title: "Catch Figures"
output: 
  word_document:
    reference_docx: output_template.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=12, fig.height=8, out.width = 600, out.height = 400)
library(funplots)
```

```{r readfiles, include = FALSE, message = FALSE, warning = FALSE}
  year =2022
  species = 'RSOL'
  area = 'BSAI'
  afsc_species = 10261
  norpac_species = 120
  akfin_user = "cmcgilliard"
  akfin_pwd = "afstar12"


    # establish akfin connection
    akfin = DBI::dbConnect(odbc::odbc(), "akfin",
                           UID = akfin_user, PWD = akfin_pwd)
   c.df<-afscdata::q_catch(year=year, species=species, area=area, db = akfin,save = FALSE) %>% dplyr::rename_with(stringr::str_to_title)


```

```{r plot total catch, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Figure 1. Time series of total catch (mt) by gear. TRW is Trawl, OTH is Other, HAL is Hook and Line, and GLN is Gillnet."}

p<-plot_total_catch(thedata = c.df,year = year,species=species,area=area)
p
```

```{r close_database, include = FALSE, message = FALSE, warning = FALSE}

    DBI::dbDisconnect(akfin)

```
